Develop
ShvetsovYura/oygophermart pull request #6
Opened 2024-03-25 16:11 UTC by ShvetsovYura

2024-03-26 20:33 UTC, Bazys requested changes
Внимательней с управлением горутинами в worler pool. Надо ими уметь управлять.
Таже не увидел обработку 429 ошибки от "черного ящика"

2024-03-26 20:33 UTC, Bazys commented on internal/services/order_service.go
> +	logger.Log.Debugf("withdraw balance: user %s %s %v", userID, orderID, balance)
```suggestion
	logger.Log.Debugf("withdraw balance: user %d %d %v", userID, orderID, balance)
```
userID, orderID у тебя же инты

2024-03-26 20:33 UTC, Bazys commented on internal/store/order_store.go
> +	logger.Log.Debugf("user %s balance %v", userID, m)
аналогично userID - инт

2024-03-26 20:33 UTC, Bazys commented on internal/services/hash_service.go
> +func (s *HashService) getSign(src []byte) ([]byte, error) {
а зачем возвращать error - он вданном случае всегда nil

2024-03-26 20:33 UTC, Bazys commented on internal/webserver/server.go
> +func NewWebServer(ctx context.Context, dbConn *pgxpool.Pool, opt *options.AppOptions) (*WebServer, error) {
а здесь зачем контекст?

2024-03-26 20:33 UTC, Bazys commented on internal/store/user_store.go
> +		} else {
у тебя с трочкой выше return. Зачем else?

2024-03-26 20:33 UTC, Bazys commented on internal/services/order_service.go
> +		} else {
else if - одной строчкой можно

2024-03-26 20:33 UTC, Bazys commented on internal/services/hash_service.go
> +	token := append(userID, sign...)
ты точно уверен что так и задумывалось? первые 8 байт в слайсе token будут пустыми.
Странная конструкция.

2024-03-26 20:33 UTC, Bazys commented on internal/utils/utils.go
> +				d1 = d1 - 9
d1 -= 9

2024-03-26 20:33 UTC, Bazys commented on internal/utils/utils.go
> +func Contains(rec models.AccrualResult, records []models.AccrualResult) bool {
щас наверное дженерик версия есть этой функции

2024-03-26 20:33 UTC, Bazys commented on internal/app/main.go
> +func Run(ctx context.Context, opts *options.AppOptions) error {
зачем возвращать ошибку, если ее не проверяешь?

2024-03-26 20:33 UTC, Bazys commented on internal/router/router.go
> +	userID := r.Context().Value(models.UIDKey).(uint64)
а если там ничего не лежит или лежит что нить, то что ты не ожидал? надо проверять на ок

2024-03-26 20:33 UTC, Bazys commented on internal/store/order_store.go
> +		rows.Scan(&m.ID, &m.UserID, &m.Status, &m.CreateedAt, &m.UpdatedAt)
опять ошибки не проверяешь

2024-03-26 20:33 UTC, Bazys commented on internal/accrual_agent/agent.go
> +			a.getAccrualInfoTick()
в бесконечном цикле по таймеру запускаешь getAccrualInfoTick() в которой порождаешь еще несколько горутин, которые тоже никак не управляются. Вот так и получают утечку горутин

2024-03-28 15:15 UTC, ShvetsovYura commented on internal/services/hash_service.go
> +	token := append(userID, sign...)
я в строке 55 в  `userID`  присваиваю `id`, который получил. Если это не верно: то могу переделать, Или вообще переделать на `JWT` -  заодно потренеруюсь. Как быть ?

2024-03-28 15:55 UTC, ShvetsovYura commented on internal/utils/utils.go
> +func Contains(rec models.AccrualResult, records []models.AccrualResult) bool {
Я не знаю как в generic можно указать, что нужно чтобы входные обхекты содержали нужные поля

2024-03-29 08:16 UTC, ShvetsovYura commented on internal/accrual_agent/agent.go
> +			a.getAccrualInfoTick()
Попытался исправить =)

2024-03-29 08:17 UTC, ShvetsovYura commented
> Внимательней с управлением горутинами в worler pool. Надо ими уметь управлять. Таже не увидел обработку 429 ошибки от "черного ящика"

Исправил замечания

2024-03-29 08:27 UTC, ShvetsovYura commented
Большое спасибо за ревью! Попытался исправить замечания. Прошу проверить как получилось (с пристрастием=)

2024-03-29 17:45 UTC, Bazys approved these changes
использование errorgroup одобряю

2024-03-30 19:02 UTC, merged